version: '3.3'

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    
  backend:
    container_name: backend
    image: alexhzzz/demo4640-backend:latest
    env_file:
      - .env
    depends_on:
      - mysql_db
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: alexhzzz/week12-frontend:latest
    env_file:
      - .env
    ports:
      - "8080:80"
    restart: unless-stopped